In [1]:
import numpy as np

In [3]:
data = np.random.randn(2,3)
data

array([[ 0.04135317, -0.10890439,  0.07117505],
       [ 0.36394725, -0.31679785, -0.8873095 ]])

In [4]:
data*10

array([[ 0.41353173, -1.08904389,  0.71175051],
       [ 3.63947253, -3.1679785 , -8.873095  ]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

 <br>

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

 <br>
 

In [10]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
np.empty((2,3,2))

array([[[  1.12754734e-311,   3.16202013e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   2.42268080e-052]],

       [[  2.57195790e+184,   8.77836281e-071],
        [  6.37575397e-067,   1.68685924e-051],
        [  1.29343749e+161,   1.16130323e-046]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

 <br>

In [27]:
arr1 = np.array([1,2,3], dtype = float)
arr2 = np.array([1,2,3], dtype = np.int64)

In [28]:
arr1.dtype
arr2.dtype

dtype('int64')

In [31]:
arr1_float = arr2.astype(np.float64)
arr1_float.dtype

dtype('float64')

In [36]:
arr3 = np.random.randn(2,3)*10
arr3

array([[ -3.90335046, -18.44421029,  -7.28493846],
       [  6.49851762,  -2.75327273,   4.54850092]])

In [40]:
arr3 = arr3.astype(int)
arr3

array([[ -3, -18,  -7],
       [  6,  -2,   4]])

 <br>

In [49]:
numeric_st = np.array(['1.1','3.3','4.4'], dtype = np.string_)
numeric_st

array([b'1.1', b'3.3', b'4.4'],
      dtype='|S3')

In [50]:
numeric_st.astype(float)

array([ 1.1,  3.3,  4.4])

In [55]:
arr4 = np.arange(10)
arr4_1 = np.array([.11, .122])
arr4.astype(arr4_1.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

 <br>

### 배열은 for 반복문을 작성하지 않고 데이터 일괄처리 가능

In [57]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [59]:
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [60]:
arr1 **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

 <br>

In [61]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

#### - numpy 배열 복사에 주의

In [66]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [67]:
arr_slice[1] = 128
arr

array([  0,   1,   2,   3,   4,  12, 128,  12,   8,   9])

In [70]:
arr_slice[:] = 1000
arr

array([   0,    1,    2,    3,    4, 1000, 1000, 1000,    8,    9])

In [72]:
arr_slice2 = arr[5:8].copy()
arr_slice2

array([1000, 1000, 1000])

In [73]:
arr_slice2[:] = [5,6,7]
arr

array([   0,    1,    2,    3,    4, 1000, 1000, 1000,    8,    9])

#### - 2차원 슬라이싱

In [75]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[0]

array([1, 2, 3])

In [77]:
arr2d[0][2]

3

In [78]:
arr2d[0,2]

3

 상기 두가지 표현법이 동일

In [79]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr3d[0][0]

array([1, 2, 3])

In [82]:
arr3d[0,0]

array([1, 2, 3])

In [86]:
arr3d[:][0][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr3d[:,0,:2]

array([[1, 2],
       [7, 8]])

In [87]:
arr3d[:,0,:2] = 0
arr3d

array([[[ 0,  0,  3],
        [ 4,  5,  6]],

       [[ 0,  0,  9],
        [10, 11, 12]]])

 <br>
 <br>

In [91]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob','Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
data

array([[-0.05505856,  0.69345061, -0.11375932, -1.26912145],
       [-0.42314183,  0.1426008 , -0.50905107,  0.23703152],
       [ 1.06889601, -0.8691763 , -0.05427974, -0.76092169],
       [-1.28825243, -0.70170801,  0.57306567,  0.6986651 ],
       [-0.41992458,  1.61336506,  0.04652878,  1.20656393],
       [ 0.4188617 ,  1.06710294, -1.89762215, -0.32619142],
       [ 0.90378937, -1.21559392,  1.21352327, -0.57400584]])

In [89]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [92]:
data[names == 'Bob']

array([[-0.05505856,  0.69345061, -0.11375932, -1.26912145],
       [-1.28825243, -0.70170801,  0.57306567,  0.6986651 ]])

**단, boolean의 길이는 축의 길이와 동일한 길이를 가져야 함**

In [99]:
data[names == 'Bob',0,0]

IndexError: too many indices for array

In [96]:
data1 = data[names == 'Bob']
data1[0, 0]

-0.055058563234913774

In [102]:
data[(names == 'Bob') | (names == 'Joe')]

array([[-0.05505856,  0.69345061, -0.11375932, -1.26912145],
       [-0.42314183,  0.1426008 , -0.50905107,  0.23703152],
       [-1.28825243, -0.70170801,  0.57306567,  0.6986651 ],
       [ 0.4188617 ,  1.06710294, -1.89762215, -0.32619142],
       [ 0.90378937, -1.21559392,  1.21352327, -0.57400584]])

In [104]:
data[data<0]=0
data

array([[ 0.        ,  0.69345061,  0.        ,  0.        ],
       [ 0.        ,  0.1426008 ,  0.        ,  0.23703152],
       [ 1.06889601,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.57306567,  0.6986651 ],
       [ 0.        ,  1.61336506,  0.04652878,  1.20656393],
       [ 0.4188617 ,  1.06710294,  0.        ,  0.        ],
       [ 0.90378937,  0.        ,  1.21352327,  0.        ]])

In [106]:
data[names == 'Joe'] = 7
data

array([[ 0.        ,  0.69345061,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.06889601,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.57306567,  0.6986651 ],
       [ 0.        ,  1.61336506,  0.04652878,  1.20656393],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])