# 4장 NumPy 기본
# 4-5 선형대수

In [2]:
import numpy as np

In [3]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
x.dtype

dtype('int32')

In [4]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [5]:
y.dtype

dtype('float64')

In [8]:
x.dot(y)

array([[  15.,   25.],
       [  54.,  142.]])

In [9]:
y.dot(x)

array([[  69.,   98.,  127.],
       [  21.,   27.,   33.],
       [  27.,   44.,   61.]])

배열1.dot(배열2)로 행렬곱셈 수행

In [10]:
np.dot(x,y)

array([[  15.,   25.],
       [  54.,  142.]])

np.dot(배열1, 배열2)도 같은 결과 출력

___

- numpy.linalg 는 행렬 관련된 명령어를 포함함

In [12]:
from numpy.linalg import inv, qr

In [14]:
X = np.random.randn(5,5)
X

array([[ 0.71131819, -1.36932718, -0.35713646, -1.11324081, -0.98403831],
       [ 0.19014304,  1.05722064,  0.33732804, -0.91101356, -0.45695391],
       [ 1.18001114, -0.6390262 ,  0.35912802, -1.18555543, -1.37187758],
       [ 0.38376588,  0.25397082, -0.10701705, -0.97857583, -0.34158284],
       [ 1.3371694 , -0.0089316 , -2.11465846,  0.06363535, -0.7132139 ]])

In [15]:
mat = X.T.dot(X)

In [17]:
inv(mat)

array([[ 16.97861533,  -1.43286003,   4.51968997,  -3.06611937,
         18.04938737],
       [ -1.43286003,   0.53337366,  -0.29512816,   0.52113453,
         -1.98242692],
       [  4.51968997,  -0.29512816,   1.61154608,  -0.28387476,
          4.13222132],
       [ -3.06611937,   0.52113453,  -0.28387476,   2.10527255,
         -5.00139944],
       [ 18.04938737,  -1.98242692,   4.13222132,  -5.00139944,
         21.51429114]])

In [18]:
mat

array([[ 3.86985249, -1.44153994, -2.63484808, -2.65451271, -3.49045742],
       [-1.44153994,  3.46570784,  0.60788268,  1.06975146,  1.66065308],
       [-2.63484808,  0.60788268,  4.85354262, -0.36534045,  1.2493719 ],
       [-2.65451271,  1.06975146, -0.36534045,  4.43645259,  3.42707882],
       [-3.49045742,  1.66065308,  1.2493719 ,  3.42707882,  3.68453926]])

# 추후 공부 필요
___

이하 선형대수 함수 명령어

함수 | 설명
---|---
numpy.diag| 대각행렬(1들로 이루어진)
numpy.dot| 행렬곱셈
numpy.trace| 행렬의 대각선 원소의 합 계산
numpy.linalg.det| 행렬식 계산
numpy.linalg.eig| 정사각 행렬의 고유 값과 고유 벡터를 계산
numpy.linalg.inv| 역행렬 계산
numpy.linalg.pinv| 무어-펜로즈 유사역원 역행렬
numpy.linalg.qr| QR 분해 계산
numpy.linalg.svd| SVD 특이값 분해 계산
numpy.linalg.solve| 행렬1x = 행렬2를 만족하는 x 계산
numpy.linalg.lstsq| y = xb를 만족하는 최소제곱해