# 4장 NumPy 기본
# 4-7 계단 오르내리기 예제

In [2]:
import numpy as np
import random

In [4]:
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

이하 예제

In [5]:
nsteps = 1000

In [8]:
draws = np.random.randint(0,2, size = nsteps)

In [9]:
steps = np.where(draws>0, 1, -1)

In [12]:
walk = steps.cumsum()

In [14]:
walk.min() 

-19

In [15]:
walk.max()

49

In [17]:
(np.abs(walk) >=10).argmax()

53

In [22]:
np.arange(1,1001)*(np.abs(walk) >=10)

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,   54,   55,
         56,    0,    0,    0,    0,    0,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,   86,    0,   88,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        100,  101,  102,  103,  104,    0,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

위의 시뮬레이션을 5000번 반복

In [35]:
nwalks = 5000
nstep = 1000
draws = np.random.randint(0,2, size = (nwalks, nstep))
steps = np.where(draws==0, -1, draws)
walks = steps.cumsum(axis = 1)
walks

array([[  1,   0,   1, ...,  62,  63,  62],
       [  1,   0,   1, ..., -30, -29, -28],
       [  1,   0,   1, ...,   4,   5,   4],
       ..., 
       [  1,   0,  -1, ..., -54, -53, -54],
       [ -1,  -2,  -1, ...,  36,  35,  36],
       [  1,   2,   3, ...,  40,  41,  40]], dtype=int32)

In [36]:
walks.max()

140

In [37]:
walks.min()

-122

In [38]:
hits30 = (np.abs(walks) >=30).any(1)
hits30

array([ True,  True, False, ...,  True,  True,  True], dtype=bool)

In [39]:
sum(hits30)

3367

In [41]:
crossing_times = (np.abs(walks) >=30).argmax(axis = 1)
crossing_times

array([261, 481,   0, ..., 507, 395, 141], dtype=int64)

In [42]:
crossing_times.mean()

336.97739999999999