# 5장 pandas 시작하기
# 5-1 pandas 자료 구조

In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

> #### 1. Series  

In [4]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

pandas의 series는 1차원 배열 같은 구조이며 index를 가지고 있음

In [7]:
obj2 = Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['d']

4

In [13]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[['c','a','b']]

c    3
a   -5
b    7
dtype: int64

index는 따로 설정 가능하며, 색인 가능

In [15]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

불리언 배열로 색인하거나 산술도 가능

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

Series는 고정 길이의 dictionary와 유사  
따라서 dictionary로 Series 구성 가능

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

사전 객체 + index로도 구성 가능하며, 이때 index가 우선순위에 놓임

In [21]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
obj4.isnull() # 인스턴스 메서드

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'Population'
obj4.index.name = 'State'
obj4

State
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

위와 같이 Series 이름과 index 이름 설정 가능

In [28]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [29]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

index 변경 가능

> #### 2. DataFrame

In [30]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [31]:
DataFrame(data, columns= ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

열 순서 배정 가능

In [32]:
frame2 = DataFrame(data,
                   columns = ['year', 'state', 'pop', 'debt'],
                  index =['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [33]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [34]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [35]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

색인은 열단위 데이터프레임['열이름'] or 데이터프레임.열이름  
행단위 데이터프레임.loc['행이름'] 으로 가능

In [37]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [38]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [39]:
frame2.loc['two'] = [2, 'Oregon', 'Oz', 'cake']
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two       2  Oregon   Oz  cake
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

열이름 또는 행이름을 대입하여 새로운 값 기입 가능

In [40]:
val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'six'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two       2  Oregon   Oz  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN

Series 대입가능 단, index가 같아야 함

In [41]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two       2  Oregon   Oz  -1.2    False
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9   NaN    False

In [42]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two       2  Oregon   Oz  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN

새로운 열 생성 및 삭제 가능

In [43]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [44]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [45]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

중첩된 dictionary로 DataFrame 생성 시 외부 사전의 키 값이 열, 내부사전의 키 값이 행이 됨  
Transpose 작동함

In [46]:
DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [47]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

Series와 마찬가지로 index이름, column 이름 지정 가능

In [48]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2, 'Oregon', 'Oz', -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan]], dtype=object)

In [49]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

데이터프레임.values는 2차원 배열을 반환
___

> #### 3. 색인 객체

In [51]:
obj = Series(range(3), index = ['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int32

In [59]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [60]:
index[1] = 'd'

TypeError: Index does not support mutable operations

- index는 변경 불가

In [61]:
index = pd.Index(np.arange(3))
index

Int64Index([0, 1, 2], dtype='int64')