In [1]:
import numpy as np

> ### numpy 배열 생성

- numpy는 파이썬의 **리스트**를 인수로 받아 배열을 반환

In [3]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [5]:
type(x)

numpy.ndarray

> ### NumPy 산술 연산

In [18]:
x = np.array([1, 2, 3])
y = np.array([2.0, 4, 6])
x

array([1, 2, 3])

In [19]:
x.dtype

dtype('int32')

In [20]:
y

array([2., 4., 6.])

In [21]:
y.dtype

dtype('float64')

In [8]:
x+y

array([3., 6., 9.])

In [9]:
x-y

array([-1., -2., -3.])

In [10]:
x/y

array([0.5, 0.5, 0.5])

- 원소 수가 같다면 (len) 산술 연산은 각 원소에 대해서 수행: element-wise
- 배열과 스칼라 값의 조합으로 된 산술 연산도 수행 가능 (후술)

> ### NumPy의 N차원 배열

In [22]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [23]:
A.shape

(2, 2)

In [24]:
A.dtype

dtype('int32')

In [ ]:
B = np.array([[3,0], [0,6]])
B

In [28]:
A+B

array([[ 4,  2],
       [ 3, 10]])

In [29]:
A*B

array([[ 3,  0],
       [ 0, 24]])

- 위의 예제와 마찬가지로 element-wise 산술연산 수행
- 브로드캐스트 기능 작동(후술)

> ___
### NumPy를 통해 N차원 배열 작성 가능  
### 1차원 배열은 **VECTOR**(벡터), 2차원 배열은 **MATRIX**(행렬),  
### 그리고 벡터와 행렬을 **일반화**한 것을 **TENSOR**(텐서)라고 지칭  
### 3차원 이상의 배열은 다차원 배열이라 지칭
___

> ### 브로드캐스트

- NumPy에서는 형상이 다른 배열끼리도 계산 가능
- 스칼라 값의 경우 배열의 shape과 같은 형대로 확대 후 연산 수행

In [3]:
A = np.array([[1,2], [3,4]])
B = np.array([10, 20])

In [4]:
A

array([[1, 2],
       [3, 4]])

In [5]:
B

array([10, 20])

In [6]:
A*B

array([[10, 40],
       [30, 80]])

- B 행렬이 (2, )에서 (2, 2) 행렬로 확대

> ### 원소 접근

In [8]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [9]:
X[0]

array([51, 55])

In [10]:
X[0][0]

51

In [11]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [12]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


- faltten은 X를 1차원 행렬로 변환(평탄화)

In [13]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [14]:
X[[0, 2, 4]]

array([51, 14,  0])

In [15]:
X > 15

array([ True,  True, False,  True, False, False])

In [16]:
X[X>15]

array([51, 55, 19])