# 12. 고급 NumPy
> ## 브로드캐스팅
___

- 다른 모양의 배열 간 산술연산

In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr *4

array([ 0,  4,  8, 12, 16])

- 배열과 스칼라 값의 결합
- 스칼라 값은 곱연산 과정에서 배열의 모든 원소로 전파(*broadcast*) 됨

In [4]:
arr = randn(4,3)
arr.mean()

0.04251402683727162

In [6]:
arr.mean(0)

array([-0.1763707 ,  0.14264253,  0.16127025])

In [7]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.1604558 , -0.49052694, -1.42390614],
       [-1.01058533, -0.13687355,  0.80112189],
       [ 0.98722778,  0.02521694, -1.05368398],
       [ 0.18381335,  0.60218355,  1.67646823]])

In [8]:
demeaned.mean(0)

array([ 3.46944695e-17,  2.77555756e-17, -5.55111512e-17])

- column의 길이가 같으므로 연산 가능

In [9]:
arr-arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

- column의 길이가 다르므로 연산 불가

In [10]:
arr-arr.mean(1).reshape(4,1)

array([[ 0.3122891 ,  0.30123119, -0.61352029],
       [-1.1140244 ,  0.07870062,  1.03532378],
       [ 0.78208947,  0.13909187, -0.92118134],
       [-0.85589309, -0.11850965,  0.97440275]])

- column의 길이를 1로 만들고 row 길이를 맞춰 브로드캐스트 연산 수행
___
## 1. 다른 축에 대해 브로드캐스팅 하기

In [14]:
arr = np.zeros((4,4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [15]:
arr_1d = np.random.normal(size = 3)
arr_1d[:, np.newaxis]

array([[0.51482246],
       [0.00207   ],
       [1.4061313 ]])

In [16]:
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [17]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- np.newaxis로 새로운 차원 축 추가 가능
- 브로드캐스팅 전용 목적으로 길이가 1인 새로운 축이 추가되는 모습

In [19]:
arr = randn(3, 4, 5)
depth_means = arr.mean(2)
depth_means

array([[-0.39758885,  0.06624664, -0.01538678,  0.27562164],
       [-0.28018709,  0.11391621, -0.07152881,  0.01905842],
       [-0.79657979, -0.27374474, -0.55651837, -0.23640015]])

In [20]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[-4.44089210e-17,  0.00000000e+00,  2.22044605e-17,
        -3.33066907e-17],
       [ 0.00000000e+00, -4.44089210e-17,  1.11022302e-17,
         8.88178420e-17],
       [-4.44089210e-17,  4.44089210e-17, -7.77156117e-17,
         0.00000000e+00]])

- 마찬가지로 3차원에서 브로드캐스팅 가능
___
## 2. 브로드캐스팅 이용해 배열에 값 대입하기

In [21]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

- 1차원 스칼라 값으로 배열에 값 대입하기는 매우 쉬움

In [22]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [23]:
arr[:2]

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42]])

In [25]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

- 다차원 배열에 값 대입하는 것 마찬가지로 위의 과정과 동일한 절차에 따라 대입 가능