# 12. 고급 NumPy
> ## NumPy matrix 클래스


In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [2]:
X = randn(16).reshape(4,4)

In [3]:
X

array([[-0.28167647,  0.90860727, -0.65304876,  0.75758635],
       [-0.9261442 ,  0.38447604, -1.17859115, -0.39803793],
       [ 0.44084365,  0.01350015,  0.92011589,  0.89576789],
       [-0.76822277, -0.6609727 ,  0.05777928, -0.60167201]])

In [6]:
X[:,0]

array([-0.28167647, -0.9261442 ,  0.44084365, -0.76822277])

- 2차원 배열에서 하나의 행이나 칼럼을 선택하면 1차원 배열을 반환

In [7]:
y = X[:, :1]
y

array([[-0.28167647],
       [-0.9261442 ],
       [ 0.44084365],
       [-0.76822277]])

In [8]:
np.dot(y.T, np.dot(X,y))

array([[-0.45007665]])

In [10]:
Xm = np.matrix(X)
ym = Xm[:,0]
Xm

matrix([[-0.28167647,  0.90860727, -0.65304876,  0.75758635],
        [-0.9261442 ,  0.38447604, -1.17859115, -0.39803793],
        [ 0.44084365,  0.01350015,  0.92011589,  0.89576789],
        [-0.76822277, -0.6609727 ,  0.05777928, -0.60167201]])

In [12]:
ym

matrix([[-0.28167647],
        [-0.9261442 ],
        [ 0.44084365],
        [-0.76822277]])

In [13]:
Xm.I*Xm

matrix([[ 1.00000000e+00, -5.32907052e-15,  0.00000000e+00,
         -7.10542736e-15],
        [-7.10542736e-15,  1.00000000e+00, -1.42108547e-14,
          5.32907052e-15],
        [-1.06581410e-14,  1.06581410e-14,  1.00000000e+00,
          5.32907052e-15],
        [ 7.10542736e-15, -7.10542736e-15,  1.42108547e-14,
          1.00000000e+00]])